name: build-test-actions
run-name: ${{ github.actor }} is running the build-test workflow
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
    branches:
      - 'main'
  
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node JS
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Install dependancies
        run: npm ci
      - name: Build code
        run: npm run build
      - name: Run unit tests
        run: npm run test