name: build-test-push-actions
run-name: ${{ github.actor }} is running the build-test workflow
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
    branches:
      - 'main'
  
jobs:
  build-test:
    name: Build and test node app
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Use Node JS
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Install dependancies
        run: npm ci
      - name: Build code
        run: npm run build
      - name: Run unit tests
        run: npm run test

  build-push-to-ecr:
    name: Build docker image and push to ecr
    runs-on: ubuntu-latest
    steps:
      - name: Check out code 
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: actions/configure-aws-credentials@v1
        with:
          aws-access-key:id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag and push image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: docker_nodejs_demo
          IMAGE_TAG: nopdejs_demo_image
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG


